#!/usr/bin/env bash
# Capture slapd's own subschema into testdata.
#
# slapd emits RFC 4512 descriptions for everything it has
# registered, which makes its output the best available oracle
# for the schema parser: if Olivine cannot read what slapd
# emits, Olivine cannot agree with slapd about the schema.
#
# Regenerate after bumping the submodule. Needs the oracle
# image, so run `make golden-build` first.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
cd "$root"

tag=$(git -C openldap describe --tags --always)
image="olivine-oracle:${tag}"
out=internal/schema/testdata/subschema.ldif

# dsee.schema is excluded on purpose: it defines the OID macro
# NetscapeRoot, which dyngroup.schema also defines, and slapd
# refuses the second definition. The two cannot be loaded
# together, which is upstream's problem and not ours.
files="core cosine inetorgperson collective corba duaconf \
dyngroup java misc namedobject nis openldap pmi"

dir=$(mktemp -d)
chmod 755 "$dir"
trap 'rm -rf "$dir"; podman rm -f olivine-subschema >/dev/null 2>&1 || true' EXIT

openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 \
	-nodes -keyout "$dir/key.pem" -out "$dir/cert.pem" \
	-days 1 -subj /CN=localhost 2>/dev/null
chmod 644 "$dir"/*.pem

{
	for f in $files; do
		echo "include /opt/openldap/etc/openldap/schema/$f.schema"
	done
	echo 'TLSCertificateFile /config/cert.pem'
	echo 'TLSCertificateKeyFile /config/key.pem'
	echo 'pidfile /data/slapd.pid'
	echo 'argsfile /data/slapd.args'
	echo 'database mdb'
	echo 'suffix "dc=example,dc=com"'
	echo 'directory /data'
} > "$dir/slapd.conf"

podman rm -f olivine-subschema >/dev/null 2>&1 || true
podman run --detach --name olivine-subschema \
	--volume "$dir:/config:ro" "$image" \
	-h "ldaps://0.0.0.0:10636/" -f /config/slapd.conf -d 0 \
	>/dev/null

for _ in $(seq 1 60); do
	if podman exec olivine-subschema sh -c \
		'LDAPTLS_REQCERT=never /opt/openldap/bin/ldapwhoami \
			-H ldaps://localhost:10636 -x' >/dev/null 2>&1
	then break; fi
	sleep 0.5
done

mkdir -p "$(dirname "$out")"
{
	echo "# Generated by scripts/capture-subschema.sh from"
	echo "# $image — do not edit by hand."
	echo "# Schema files: $files"
	podman exec olivine-subschema sh -c \
		'LDAPTLS_REQCERT=never /opt/openldap/bin/ldapsearch \
			-H ldaps://localhost:10636 -x -b cn=Subschema \
			-s base -LLL -o ldif-wrap=no \
			attributeTypes objectClasses 2>/dev/null'
} > "$out"

echo "capture-subschema: wrote $out"
grep -c '^attributeTypes:' "$out" | sed 's/^/  attributeTypes: /'
grep -c '^objectClasses:' "$out" | sed 's/^/  objectClasses:  /'
