#!/usr/bin/env bash
# Capture slapdn's DN normalisation into testdata.
#
# slapdn runs slapd's own dnNormalize and dnPretty, so it is a
# direct oracle for internal/dn: no guessing about what the C
# does with escapes, spacing or case.
#
# Regenerate after bumping the submodule. Needs the oracle
# image, so run `make golden-build` first.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
cd "$root"

tag=$(git -C openldap describe --tags --always)
image="olivine-oracle:${tag}"
cases=internal/dn/testdata/cases.txt
out=internal/dn/testdata/normalised.txt

if [ ! -f "$cases" ]; then
	echo "missing $cases" >&2
	exit 1
fi

dir=$(mktemp -d)
chmod 755 "$dir"
trap 'rm -rf "$dir"' EXIT
printf 'include %s/core.schema\n' \
	/opt/openldap/etc/openldap/schema > "$dir/slapd.conf"
cp "$cases" "$dir/cases.txt"
chmod 644 "$dir/cases.txt"

# The loop runs inside the container: slapdn invoked once per
# DN, so a rejected DN cannot shift the lines of the ones after
# it. slapdn prints failures to stderr and successes to stdout,
# which would otherwise misalign the whole corpus.
cat > "$dir/run.sh" <<'INNER'
#!/bin/sh
slapdn=/opt/openldap/sbin/slapdn
# printf, never echo: dash's echo interprets backslash
# escapes, so `echo "cn=a\2C b"` emits a raw 0x02 byte and
# silently corrupts every hex escape in the corpus.
one() {
	out=$("$slapdn" -f /config/slapd.conf "$1" "$2" 2>/dev/null \
		| head -1)
	if [ -z "$out" ]; then
		printf 'INVALID\n'
	else
		printf '%s\n' "$out"
	fi
}
while IFS= read -r dn; do
	case "$dn" in ''|'#'*) continue ;; esac
	printf '%s\t%s\t%s\n' "$dn" "$(one -N "$dn")" \
		"$(one -P "$dn")"
done < /config/cases.txt
INNER
chmod 755 "$dir/run.sh"

{
	echo "# Generated by scripts/capture-dn.sh from $image"
	echo "# Do not edit by hand. Tab-separated:"
	echo "#   input <TAB> normalised <TAB> pretty"
	echo "# INVALID means slapdn rejected the DN."
	podman run --rm --volume "$dir:/config:ro" \
		--entrypoint /bin/sh "$image" /config/run.sh
} > "$out"

echo "capture-dn: wrote $out ($(grep -cv '^#' "$out") cases)"
