name: Build

on:
  push:
    branches:
      - mother

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: false

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.0'

    - name: Install dependencies
      run: go mod download

    - name: Build binary
      run: make build

    #- name: Build the Olivine container image
    #  run: make pod-build
